# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for tqdm
  - package-ecosystem: "tqdm"
    directory: "/" # Location of package manifests
    # Check the tqdm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for requests
  - package-ecosystem: "requests"
    directory: "/" # Location of package manifests
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
